### ISSUE TITLE
Wrong Enddate shown

### ISSUE THREAD

**Issue by bebablub** [syssi/es-f#11]
Hello,

i'm using es-f/2.6.1+syssi1 (2013-11-13). Until a few weeks ago everything worked fine. But now i cannot start auctions anymore because end date is parsed wrong. For example:

http://www.ebay.de/itm/Samsung-850-EVO-1-TB-Intern-6-35-cm-2-5-Zoll-MZ-75E1T0B-EU-SSD-Solid-/131752115996?hash=item1ead09bf1c:g:~i0AAOSwmmxW5opz

Real Enddate: 21. Mrz. 2016 10:55:01 MEZ
Enddate in es-f: 2015-12-21 10:55:01

So es-f thinks the status of the auction is already ended...

Any ideas? Could plz anyone help?

Thank you!

**Comment by bebablub** [comment]
have found a fix for my own see file:
de.class.php
line 28 should look like: 
$months = array( 'Jan' => 1, 'Feb' => 2, 'Mrz' => 3, 'Apr' => 4, 'Mai' => 5, 'Jun' => 6, 'Jul' => 7, 'Aug' => 8, 'Sep' => 9, 'Okt' => 10, 'Nov' => 11, 'Dez' => 12 );

the short term of march is different...

**Comment by Velociraptor85** [comment]
@bebablub since its an array I would just add the **Mrz** string to it, but thanks for the solution.

**Comment by Velociraptor85** [comment]
@syssi @bebablub should be fixed with last commit please check and close

**Comment by syssi** [comment]
Works fine!
