### ISSUE TITLE
Wrong current item price while parsing ebay.de

### ISSUE THREAD

**Issue by bebablub** [syssi/es-f#13]
Hello,

thank you very much for your work and this nice script. Unfortunatly theres a error while parsing current item price. For example: 
http://www.ebay.de/itm/122037796024
Parsing this auction gives me "?" as current item price. Probably the reg ex at es-f/application/classes/ebayparser/main.xml is wrong:

    <pattern name="bid">
      <![CDATA[
      ~<font size="-1" color="#666666">(.+?)</span>~i => 1
      ~<div .*id="v4-31"[^>]*>(.+?)</~i => 1
      ~<span .*id="v4-26"[^>]*>(.+?)</~i => 1
      ~<span .*id=.* itemprop="price">(.+?)</~i => 1
      ~<span id="" class="notranslate vi-VR-cvipPrice">(.+?)</span>~i => 1
      ]]>
    </pattern>

But as for the moment i don't have any idea on how to fix that. Probably you can help?

Thank you very much!

**Comment by bebablub** [comment]
adding ~<span class="notranslate" id="prcIsum_bidPrice" itemprop="price" content="(.+?)">(.+?)</span>~i => 1 makes it better, but currency is still a "?"

**Comment by bebablub** [comment]
> ~<span class="notranslate" id="prcIsum_bidPrice" itemprop="price" content="(.+?)">(.+?)</span>~i => 1

**Comment by bebablub** [comment]
`~<span class="notranslate" id="prcIsum_bidPrice" itemprop="price" content="(.+?)">(.+?)</span>~i => 1` makes it better, but currency is still a ?

**Comment by bebablub** [comment]
i think:
`~<span class="notranslate" id="prcIsum_bidPrice" itemprop="price" content="[^>]*">(.+?)</span>~i => 1`
is totally fixing it :)

**Comment by syssi** [comment]
Thanks for your hint. I will fix it asap.

**Comment by syssi** [comment]
Fixed!
