### ISSUE TITLE
The /e modifier is deprecated, use preg_replace_callback instead

### ISSUE THREAD

**Issue by laclaro** [syssi/es-f#14]
Hi,

as I run php 5.5.9, I have problems getting es-f to run. The replacements statements in plugin/compress/plugin.class.php do not work anymore.

Has anyone a solution for replacing these statements with the preg_replace_callback function?

Best regards,

Henning

**Comment by syssi** [comment]
Hi Henning,

I've refactored the mentioned lines of code. Please give it a try!

Kind regards,

Sebastian

**Comment by Velociraptor85** [comment]
@laclaro would you test the changes please and report back? then maybe @syssi you could make a new release?

**Comment by laclaro** [comment]
It works. Thank you! However, I got some issues on login now. Yesterday there have been none... not sure why now. See https://github.com/syssi/es-f/issues/15
