### ISSUE TITLE
[Error] ATTENTION: esniper encountered a bug.

### ISSUE THREAD

**Issue by laclaro** [syssi/es-f#19]
Hi,

the item http://www.ebay.de/itm/292515832239 does not work and throws a bug message. If I check the looged file it is a html page that shows the bidding history with prices in dollars. How to debug?

Best,

Henning

**Comment by Matzeee** [comment]
Probably: https://sourceforge.net/p/esniper/bugs/746/#3c3b

I like to use checkinstall, but maybe you can also just install ontop.
If I remeber correctly, I had to manually create or delete a folder. But the errormessage was pretty much selfexplaining.

```
sudo aptitude install checkinstall
git clone https://git.code.sf.net/p/esniper/git <targetdir>
cd <targetdir>
./configure
make
sudo checkinstall
make distclean (optional)
```

To upgrade:

```
sudo dpkg -r esniper
cd <targetdir>
git pull
./configure
make
sudo checkinstall
