### ISSUE TITLE
Ended Auctions don't show final bid

### ISSUE THREAD

**Issue by Steph71** [syssi/es-f#7]
Hi, 

I use 792694a315c03a390292802ea82a8ec2210a1686 and it works fine for me.

However on ended auctions the winning end price is not displayed. due to this fact also the Analysis features do not work as intended
![es_f](https://cloud.githubusercontent.com/assets/8713992/4207636/ab3861b2-3858-11e4-8bbc-6bd67440437e.jpg)

Would be nice, if this could be fixed at some point in time.

Best Regards
Stephan

**Comment by Velociraptor85** [comment]
@Steph71 do you still have this error ?

**Comment by Velociraptor85** [comment]
should be fixed by https://github.com/syssi/es-f/pull/10
